name: student_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  sqflite_common_ffi: ^2.3.2+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3
  sqflite: ^2.3.2
  google_generative_ai: ^0.2.0
  flutter_quill: ^9.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
